### ISSUE TITLE
Evitar erros com user/repo existente

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-ci#15]
Erro no Gotrue por e-mail já cadastrado ou GitHub por repo existente estão ocorrendo com certa frequência, me parece importante que:

1. Se o usuário já existir no Gotrue atualizamos a senha (desta forma o user poderá acessar mais de um repo ou permedos o anterior se houver?);
2. Antes de criar o repo no GitHub e site no Netlify, podemos listar todos os repos da org e verificar se o nome já esta sendo usado, se já estiver adicionamos um número randômicos na frente;

**Comment by thiagoabreudev** [comment]
https://github.com/thiagoabreudev/storefront-ci/pull/10

**Comment by leomp12** [comment]
Remover cadastros no Gotrue com e-mail lojathiago* ou *@lojathiago.com

**Comment by leomp12** [comment]
```bash
git subtree pull --prefix src https://github.com/thiagoabreudev/storefront-ci.git master --squash
```
