### ISSUE TITLE
Múltilos arquivos de log

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-ci#17]
Em alguns locais estamos usando um arquivo definido a partir da env `STOREFRONT_CI_LOG_PATH`, em outros lugares utiliza-se o [`console-files`](https://github.com/leomp12/console-files) que utiliza outras envs e arquivos separados para output/erro.

Sem critério pra esta diferenciação só gera confusão, com certeza com o tempo algum dos dois logs deixará de ser acompanhado, então acho que o ideal é manter só o `console-files` OU o `./config/winston.js`, não ambos...

**Comment by thiagoabreudev** [comment]
Resolvido neste commit https://github.com/thiagoabreudev/storefront-ci/commit/9e7791a1801c694dc4781af58a3a6e090abf3d8e
