### ISSUE TITLE
Instâncias duplicadas para mesma loja no Gitgateway

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-ci#24]
Em algumas ocasiões o repositório anterior é deletado (quando há algum erro) e é feito um novo deploy, o usuário é atualizado no Gotrue mas no Gitgateway ficam duas instâncias para o mesmo `store_id` (`roles`), o admin consegue logar mas às vezes bate primeiro a instância antiga no Gitgateway, aponta para o repo deletado e fica dando 404 :neutral_face: 

Quando isto acontece o CMS não tem como ser acessado até que a instância errada seja deletada, minha sugestão é deletar as instâncias com o mesmo `store_id` diretamente no banco (SQLite) do Gitgateway a cada deploy, ou seja, se é feito um novo deploy da loja 1011, as rows `where raw_base_config like "%"roles":["s1011"]"%` (não testei e talvez haja uma query melhor) devem ser deletadas antes da nova instância ser inserida.

**Comment by thiagoabreudev** [comment]
@leomp12  https://github.com/thiagoabreudev/storefront-ci/pull/16

**Comment by thiagoabreudev** [comment]
- Foi ajustado para remover a instancia do git-gateway antes de criar a nova instancia.- 
- Foi criado uma nova variável de ambiente `STOREFRONT_CI_GIT_GATEWAY_DB_PATH` onde deve-se passar o caminho do arquivo do banco de dados do git-gateway
- Foi incluído a lib sqlite3, com isso é preciso dar um npm install
