### ISSUE TITLE
Subdomínio duplicado no Netlify

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-ci#3]
Acho que precisamos verificar o dubdomínio no Netlify antes de criar o site, ou tratar o erro e fazer uma retentativa inserindo `-${Math.random() * (9999 - 1000) + 1000}` (ou algo do tipo) no subdomínio.

O erro retornado no deply:

```json
{
    "setep": "netlify",
    "status": 422,
    "error": "Unprocessable Entity",
    "details": {
        "subdomain": [
            "must be unique"
        ]
    }
}
```

> Acho que também seria `step` em vez de `setep` :stuck_out_tongue:

**Comment by thiagoabreudev** [comment]
https://github.com/thiagoabreudev/storefront-ci/pull/7
