### ISSUE TITLE
Commit duplicado

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-ci#4]
O ideal seria apenas um commit com as duas alterações de uma vez:

https://github.com/ecomplus-stores/test-ci/commit/750a3ea3bf88dbdec1e4707abdfc2a6c1ed30639
https://github.com/ecomplus-stores/test-ci/commit/d7a51d3080b790fafc1d3637442dc946d2a8a060

**Comment by thiagoabreudev** [comment]
Como conversamos, irá continuar fazendo dois commits, mas de forma sequencial, onde o primeiro irá criar o `template/public/admin/config.json` com a descrição `chore(cms): setup custom backend config [skip ci]` e o segundo irá alterar as configurações de content/settings.json .
