### ISSUE TITLE
[GITGATEWAY] Endpoints padrão retornam 404 (multi instância ?)

### ISSUE THREAD

**Issue by leomp12** [ecomplus/storefront-ci#6]
@thiagoabreudev deu pra caminhar um bocado na base do empirismo :smile: 
O login no CMS tá indo (meio gambiarra mas tá), é necessário alterar o commit 'Setup store' mas eu abro outro issue pra isto depois.

Ainda não consigo entrar no CMS porque o Git Gateway retorna 404:

https://test-6134.netlify.com/admin/#/
test6134@e-com.club : `teste`

Pode ver no network do console que ele chega a logar, pega o access token e quando faz a primeira requisição no git gateway pra pegar o conteúdo do repo, o endpoint retorna 404.
Este endpoint:
https://gitgateway.ecomplus.biz/1056/.netlify/git/github/branches/master?ts=1583559623432

Talvez isto ocorra por causa das muli instâncias, não sei o endpoint poderia mudar neste caso. O proxy está repassando `github/branches/master?ts=1583559623432`.

Alguma ideia?

**Comment by thiagoabreudev** [comment]
Boa @leomp12 . Ta quase então!

O problema me parece pelo fato da instancia não estar sendo passada no header com o parâmetro `x-store-id` (Lembra desse cara?). Com isso ele acaba caindo aqui https://github.com/ecomclub/git-gateway/blob/master/api/middleware.go#L48. 

Será que vamos ter que dar um fork no widget do netlify e setar isso?

**Comment by leomp12** [comment]
Só pra registrar o que conversamos, falta tratar o `X-Store ID` (com o ID da loja mesmo) no Git Gateway, certo @thiagoabreudev ? Então vamos pegar o ID da instância em função do ID da loja...
